[akm] small speedup and minor text changes

diff --git a/akm/akm b/akm/akm
--- a/akm/akm
+++ b/akm/akm
@@ -21,16 +21,16 @@ Header() {
     local hdr="<b>$fname</b>"
 
     if [ "$fname" = "$(RepoType)" ] ; then
-        hdr+=" (current)"
+        hdr="<i>$hdr</i>"                    # currently used repo: italics font
     fi
     FormatVersion "$hdr"
 }
 
 LocalVersion() {
-    local pkg="$(/usr/bin/basename "$1")"
+    local pkg="${1##*/}"     # "$(/usr/bin/basename "$1")"
     expac -Q %v "$pkg"       # $pacman -Q "$pkg" 2>/dev/null | /usr/bin/awk '{print $2}'
 }
-Exist()        { test -n "$version" && echo TRUE || echo FALSE ; }
+Exist()        { [ -n "$version" ] && echo TRUE || echo FALSE ; }
 
 Choose() {
     local version exist xx
@@ -59,21 +59,22 @@ Installed() {
         *) DIE "Internal error, cannot determine the running kernel." ;;
     esac
     local running=$(expac -Q %v $kernel)     # $(pacman -Q $kernel | awk '{print $2}')
-    local ind
-    cmd+=(--field="${smallBegin}$(Header)${smallEnd}!Installed kernel package versions. A * marks the currently running kernel. A bolded string means the latest K.o. version":LBL "")
+    local ind1 ind2
+    cmd+=(--field="${smallBegin}$(Header)${smallEnd}!Installed kernel package versions. The currently running kernel is in <i>italics</i>. A <b>bolded</b> string means the latest K.o. version.":LBL "")
     for xx in "${kernels[@]}" ; do
         version="$(LocalVersion "$xx")"
-        ind=""
+        ind1=""
+        ind2=""
         if [ "$version" = "$running" ] ; then
             case "$xx" in
                 *-headers) ;;
-                *) ind=" <tt>$km</tt>"
+                *) ind1="<i>"; ind2="</i>" ;;       # currently running kernel: italics font
             esac
         fi
         if IsLatestKO "$version" ; then
-            cmd+=(--field="${smallBegin}$(FormatVersion "<b>$version</b>" "$ind")${smallEnd}":LBL "")
+            cmd+=(--field="${smallBegin}$(FormatVersion "$ind1<b>$version</b>$ind2")${smallEnd}":LBL "")
         else
-            cmd+=(--field="${smallBegin}$(FormatVersion "$version" "$ind")${smallEnd}":LBL "")
+            cmd+=(--field="${smallBegin}$(FormatVersion "$ind1$version$ind2")${smallEnd}":LBL "")
         fi
     done
 }
@@ -93,8 +94,11 @@ StableVersion() {
 }
 
 Stable() {
-    local version xx
-    cmd+=(--field="${smallBegin}$(Header)${smallEnd}!Versions available from the stable repos":LBL "")
+    local version xx in_use=""
+    if [ "$FUNCNAME" = "$(RepoType)" ] ; then
+        in_use=" (currently in use)"
+    fi
+    cmd+=(--field="${smallBegin}$(Header)${smallEnd}!Versions available from the stable repos$in_use":LBL "")
     for xx in "${kernels[@]}" ; do
         version="$(StableVersion "$xx")"
         cmd+=(--field="${smallBegin}$(FormatVersion "$version")${smallEnd}":LBL "")
@@ -102,18 +106,22 @@ Stable() {
 }
 
 TestingVersion() {
-    local pkg="$(/usr/bin/basename "$1")"
+    local pkg="${1##*/}"   #"$(/usr/bin/basename "$1")"
     echo "$testinginfo" | grep -A2 /packages/testing/x86_64/$pkg/ | tail -n 1 | sed 's|^.*>\([0-9][0-9a-z\.\-]*\)<.*$|\1|'
 }
 
 Testing() {
+    local in_use=""
+    if [ "$FUNCNAME" = "$(RepoType)" ] ; then
+        in_use=" (currently in use)"
+    fi
     local URL="https://archlinux.org/packages/?sort=&repo=Testing&q=linux+kernel+and+modules"
     local testinginfo="$(/usr/bin/curl -s $URL_timeout $URL)"
     local version xx
 
     [ -n "$testinginfo" ] || DIE "Fetching info from https://archlinux.org failed!"
 
-    cmd+=(--field="${smallBegin}$(Header)${smallEnd}!Versions available from the testing repos":LBL "")
+    cmd+=(--field="${smallBegin}$(Header)${smallEnd}!Versions available from the testing repos$in_use":LBL "")
     for xx in "${kernels[@]}" ; do
         version="$(TestingVersion "$xx")"
         test -n "$version" || version="$na"
@@ -144,7 +152,7 @@ KernelOrg() {
             ((count--))
         done
     done
-    PaddingLines
+    PaddingLines $count
 }
 
 KOVersion() {
@@ -168,7 +176,7 @@ KOVersion() {
                 ;;
         esac
     done
-    PaddingLines
+    PaddingLines $count
 }
 
 IsLatestKO() {
@@ -189,6 +197,8 @@ IsLatestKO() {
 }
 
 PaddingLines() {
+    local count="$1"
+    local xx
     for ((xx=0; xx<count; xx++)) ; do
         cmd+=(--field="${smallBegin}$(FormatVersion "")${smallEnd}":LBL "")
     done
@@ -420,23 +430,25 @@ Main()
     local km="*"
 
     t1+="$smallBegin"
-    t1+="Here you'll see information about currently installed and available Linux kernels.\n"
-    t1+="You can install and/or uninstall kernel packages using the checkboxes on the leftmost column.\n"
+    t1+="Here's information about currently installed and available Linux kernels.\n"
+    t1+="Install and/or uninstall kernel packages using the checkboxes on the leftmost column.\n"
     t1+="\n"
     if [ "$small_font" = "no" ] ; then
         t1+="Column headers:\n"
         t1+="<tt>"
         t1+="    Choose        Checkboxes for installing/uninstalling kernel packages.\n"
+        t1+="                  The installed packages are checked at start.\n"
         t1+="    PkgName       Kernel package name.\n"
-        t1+="    Installed     Installed kernel package versions. A $km marks the currently running kernel.\n"
-        t1+="                  A bolded string means the latest K.o. version.\n"
+        t1+="    Installed     Installed kernel package versions.\n"
+        t1+="                  The currently running kernel is printed in italics.\n"
+        t1+="                  The latest kernel.org version is printed in bold.\n"
         t1+="    Stable        Versions available from the stable repos.\n"
         t1+="    Testing       Versions available from the testing repos.\n"
         t1+="    $KOName  Kernel category at kernel.org.\n"
         t1+="    $KOVersionName   Latest version announced at kernel.org.\n\n"
         t1+="</tt>"
     fi
-    t1+="Your current repos are either Stable or Testing (see /etc/pacman.conf).\n"
+    t1+="Your currently used repo (Stable or Testing) is printed in italics (see also /etc/pacman.conf).\n"
     t1+="Marking <b>$na</b> means: info not available.\n"
     if [ "$connect_header_with_kernel" = "yes" ] ; then
         t1+="\n"
@@ -478,26 +490,27 @@ Main()
         --text="Fetching information, please wait..."
     )
     local ix=1 count=${#functions[@]} val
-    local cmdfile="$(mktemp $HOME/.config/akm.tmp.XXXXX)"
-    while true ; do
-        for xx in "${functions[@]}" ; do
-            echo "#$xx"
-            val="$(( ix < count ? ix*100/count : 99 ))"
+    local cmdfile="$(mktemp $HOME/.cache/akm.tmp.XXXXX)"    # will gather the whole value of 'cmd' into this file (used due to the progress window)
+
+    if [ -z "$kernelorg" ] ; then
+        kernelorg="$(/usr/bin/curl -s $URL_timeout $URL)"    
+        test -n "$kernelorg" || DIE "Fetching info from $URL failed.\n"
+    fi
+
+    {
+        local func1
+        for func1 in "${functions[@]}" ; do
+            $func1 || DIE "Function '$func1' failed.\n"     # run each function to add stuff to the '$cmd'
+
+            val="$(( ix < count ? ix*100/count : 99 ))"     # progress window stuff
             ((ix++))
-            echo "$val"
-            if [ -z "$kernelorg" ] ; then
-                kernelorg="$(/usr/bin/curl -s $URL_timeout $URL)"    
-                test -n "$kernelorg" || DIE "Fetching info from $URL failed.\n"
-            fi
-            $xx || DIE "Function '$xx' failed.\n"
+            printf "#%s\n%s\n" "$func1" "$val"
         done
-        echo "#===> Done."
-        # read -p "Press ENTER: " >&2  # testing only
-        echo 100
-        printf "%s\n" "${cmd[@]}" > "$cmdfile"
-        break
-    done | "${progress_cmd[@]}"
-    readarray -t cmd <<< $(cat "$cmdfile")
+        printf "%s\n" "${cmd[@]}" > "$cmdfile"              # now print the gathered value of 'cmd' into $cmdfile
+        printf "#===> Done.\n100\n"                         # stop the progress window
+    } | "${progress_cmd[@]}"
+
+    readarray -t cmd <<< $(cat "$cmdfile")                  # now get the full 'cmd' from the file
     rm -f "$cmdfile"
     
     local installed install=() uninstall=() pkg partner result result1="" retval
