[fetch-iso] show more info about failures (like a password problem etc.)

diff --git a/fetch-iso/fetch-iso b/fetch-iso/fetch-iso
--- a/fetch-iso/fetch-iso
+++ b/fetch-iso/fetch-iso
@@ -1,8 +1,15 @@
 #!/bin/bash
 
+source /etc/eos-color.conf
+
 echo2() { echo -e "$@" >&2 ; }
+errorline() {
+    eos-color error 2
+    echo2 "$@"
+    eos-color reset 2
+}
 DIE() {
-    echo2 "$progname: error: $1"
+    errorline "==> Error [$progname]:\n    $1"
     [ "$2" ] && exit "$2" || exit 1
 }
 
@@ -247,10 +254,21 @@ Main() {
     local subdir=""
     while true ; do
         # keep the names of files, drop other info
-        items=$(${progname}-show-all-info "$subdir" | "${fzf[@]}")
-        case "$?" in
+        items=$(${progname}-show-all-info "$subdir") || exitcode=$?
+        case "$exitcode" in
+            0) ;;
             130) exit 1 ;;   # interrupted
+            *)
+                local string="$(curl-exit-code-to-string "$exitcode" "$APP")"
+                if [ "$string" ] ; then
+                    DIE "$APP: '$string'"
+                else
+                    DIE "Failed connecting to $URLBASE ($APP exit code $exitcode)."
+                fi
+                ;;
         esac
+        items=$(echo "$items" | "${fzf[@]}")
+        [ "$items" ] || exit 0                        # nothing selected
         items=$(echo "$items" | awk '{print $1}')
 
         for selected in $items ; do
diff --git a/fetch-iso/fetch-iso-show-all-info b/fetch-iso/fetch-iso-show-all-info
--- a/fetch-iso/fetch-iso-show-all-info
+++ b/fetch-iso/fetch-iso-show-all-info
@@ -1,11 +1,14 @@
 #!/bin/bash
 
 DIE() {
-    echo "$progname: error: $1" >&2
-    exit 1
+    eos-color error 2
+    echo -e "==> Error [$progname]:\n    $1" >&2
+    eos-color reset 2
+    [ "$2" ] && exit $2 || exit 1
 }
 
 Main() {
+    local -r progname=${0##*/}
     local subdir="$1"
     local dir=""
     local data
@@ -25,7 +28,7 @@ Main() {
         if [ "$ACCOUNT$PASSWORD" ] ; then
             HELLO="$ACCOUNT:$PASSWORD"
         else
-            DIE "no account/password"
+            DIE "No account/password"
         fi
     fi
 
@@ -35,8 +38,8 @@ Main() {
     esac
 
     case "$APP" in
-        curl) data=$(/bin/curl --fail -Lsm 30 -o- -u "$HELLO" "$dir")                      || DIE "failed fetching the info page '$dir'." ;;
-        wget) data=$(/bin/wget -qO - --user "${HELLO%:*}" --password "${HELLO#*:}" "$dir") || DIE "failed fetching the info page '$dir'." ;;
+        curl) data=$(/bin/curl --fail -Lsm 30 -o- -u "$HELLO" "$dir")                      || DIE "Failed fetching the info page '$dir'." "$?" ;;
+        wget) data=$(/bin/wget -qO - --user "${HELLO%:*}" --password "${HELLO#*:}" "$dir") || DIE "Failed fetching the info page '$dir'." "$?" ;;
     esac
     # data=$(echo "$data" | grep -P 'alt="\[   \]"|alt="\[DIR\]"|alt="\[PARENTDIR\]"')
     data=$(echo "$data" | grep -P 'alt="\[   \]"|alt="\[DIR\]"')
