minor bug fix for su-c_wrapper

diff --git a/welcome/su-c_wrapper b/welcome/su-c_wrapper
--- a/welcome/su-c_wrapper
+++ b/welcome/su-c_wrapper
@@ -4,7 +4,7 @@
 # (understands spaces in command parameters).
 
 Usage() {
-    echo "Usage: $(basename $0) command-with-parameters" >&2
+    echo "Usage: $progname command-with-parameters" >&2
 }
 
 DIE() {
@@ -14,8 +14,12 @@ DIE() {
 }
 
 Main() {
+    local progname="su-c_wrapper"
     local command=()
-    local xx error
+    local xx result=0
+    local subresultfile="$(mktemp -u $HOME/$progname.$(date +%s%N).XXXXX)"
+    local owner="$LOGNAME:users"
+    local subresult=0
 
     test -z "$1" && DIE "command missing"
 
@@ -27,13 +31,26 @@ Main() {
     # run max 3 times
     for xx in {2..0} ; do
         printf "Root "
-        /usr/bin/su -c "${command[*]}"
-        error=$?
-        case $error in
-            0) break ;;                # OK
-            127|126) break ;;          # command is erroneous or can't be executed
-            1) ;;                      # probably wrong password
-            *) ;;                      # signal killed command
+        LANG=C /usr/bin/su -c "${command[*]} ; echo $? > '$subresultfile' ; chown $owner '$subresultfile'"
+
+        result=$?
+        if [ -r "$subresultfile" ] ; then
+            subresult="$(cat "$subresultfile")"
+            rm -f "$subresultfile"
+        fi
+
+        case "$result" in
+            0)                       # OK
+                break ;;
+            127|126)                 # command is erroneous or can't be executed
+                break ;;
+            1)                       # wrong password or subcommand failure
+                case $subresult in
+                    0) ;;            # wrong password
+                    *) break ;;      # subcommand failure
+                esac
+                ;;
+            *) ;;                    # signal killed command
         esac
         if [ $xx -ne 0 ] ; then
             echo "Sorry, try again ($xx)." >&2
