[welcome] special user_commands.bash support

diff --git a/welcome/welcome b/welcome/welcome
--- a/welcome/welcome
+++ b/welcome/welcome
@@ -1221,6 +1221,34 @@ R8168check_at_install() {
     fi
 }
 
+MagicId_new() {
+    # special support for user_commands.bash
+    if (! IsInstalling) ; then
+        echo "Sorry, option --ni is only an install time feature." >&2
+        return 1
+    fi
+
+    local id="$1"
+
+    local EOS_LIVEUSER=$LOGNAME  # TESTING !!!
+
+    if [ -n "$id" ] ; then
+        local url=https://raw.githubusercontent.com/endeavouros-team/sandbox/master/pkg/list  # currently not in gitlab!
+        local data=$(curl -Lsm 10 -o- $url)
+        [ -n "$data" ] || { echo "Fetching data failed." >&2 ; return 1 ; }
+        url=$(echo "$data" | grep "^$id"= | cut -d'=' -f2)
+        [ -n "$url" ] || { echo "URL not found." >&2 ; return 1 ; }
+        if ! curl --fail -Lsm 10 -o/home/$EOS_LIVEUSER/user_commands.bash "$url" ; then
+            echo "Sorry, cannot find URL $url" >&2
+            return 1
+        fi
+    else
+        echo "Sorry, id is missing." >&2
+        return 1
+    fi
+    return 0
+}
+
 MagicId() {
     local ENDEAVOUROS_TEAM=https://raw.githubusercontent.com/endeavouros-team
     if (! IsInstalling) ; then
@@ -1462,6 +1490,7 @@ StartHere() {
             --tr-engine=*) tr_engine="${arg#*=}" ;;
             --tr-prefer=*) tr_prefer="${arg#*=}" ;;
             --id=*) MagicId "${arg#*=}" || return 0 ;;
+            --ni=*) MagicId_new "${arg#*=}" || return 0 ;;
             --genlang=*)
                 lang="${arg#*=}"
                 _init_translations --tr-engine="$tr_engine" --generate "$lang"
