removed code that tries to copy Welcome's install log to the target system

diff --git a/welcome/welcome b/welcome/welcome
--- a/welcome/welcome
+++ b/welcome/welcome
@@ -411,16 +411,18 @@ EOF
         yad_tailer $PACMAN_LOG
     fi
 
-    # Copy install log to /var/log of the installed system.
-    # Note: if $only_one_output_window != yes, this fails.
+    if [ 0 -eq 1 ] ; then
+        # Copy install log to /var/log of the installed system.
+        # Note: if $only_one_output_window != yes, this fails.
 
-    local varlog="$(/usr/bin/ls -d /tmp/calamares-root-*/var/log)"
-    if [ -d "$varlog" ] ; then
-        echo "Copying install log to /var/log/$(/usr/bin/basename $INSTALL_LOG_FILE) of the new install." >&2
-        cp $INSTALL_LOG_FILE $varlog
+        local varlog="$(/usr/bin/ls -d /tmp/calamares-root-*/var/log)"
+        if [ -d "$varlog" ] ; then
+            echo "Copying install log to /var/log/$(/usr/bin/basename $INSTALL_LOG_FILE) of the new install." >&2
+            cp $INSTALL_LOG_FILE $varlog
+        fi
+
+        # test $netlog -eq 1 && cat $INSTALL_LOG_FILE | curl -F 'f:1=<-' ix.io
     fi
-
-    # test $netlog -eq 1 && cat $INSTALL_LOG_FILE | curl -F 'f:1=<-' ix.io
 }
 export -f yad_calamares
 
