made usage of eos-wallpaer-set a bit easier

diff --git a/eos-bash-shared/eos-wallpaper-set b/eos-bash-shared/eos-wallpaper-set
--- a/eos-bash-shared/eos-wallpaper-set
+++ b/eos-bash-shared/eos-wallpaper-set
@@ -8,14 +8,13 @@
 
 #################################################################################
 EOS_SCRIPTS_YAD=/usr/share/endeavouros/scripts/eos-script-lib-yad
-test -r  $EOS_SCRIPTS_YAD || {
-    echo "ERROR: cannot find $EOS_SCRIPTS_YAD" >&2
+source $EOS_SCRIPTS_YAD || {
+    echo "ERROR: cannot read $EOS_SCRIPTS_YAD" >&2
     exit 1
 }
-source $EOS_SCRIPTS_YAD
 unset EOS_SCRIPTS_YAD
 
-#export -f eos_yad
+export -f eos_yad
 export -f eos_yad_terminal
 export -f eos_yad_check_internet_connection
 export -f eos_yad_GetArgVal
@@ -28,7 +27,7 @@ export -f eos_yad_GetDesktopName
 export -f eos_GetArch
 #################################################################################
 
-eos_yad() { GDK_BACKEND=x11 /usr/bin/yad --window-icon=$EOS_WICON "$@" ; }
+#eos_yad() { GDK_BACKEND=x11 /usr/bin/yad --window-icon=$EOS_WICON "$@" ; }
 
 eos_yad_infomsg() {
     local msg="$1"
@@ -109,45 +108,43 @@ WallpaperSetCommon() {
     test -n "$pic" || DIE "no picture!"
     test -n "$DE"  || DIE "no DE!"
 
-    echo "Setting desktop wallpaper for '$DE' ..." >&2
-
     case "$DE" in
         BUDGIE)
-            AssertPicture
+            AssertPicture endeavouros_budgie.png
             gsettings set org.gnome.desktop.background picture-uri "$pic"
             ;;
         CINNAMON)
-            AssertPicture
+            AssertPicture endeavouros_cinnamon.png
             gsettings set org.cinnamon.desktop.background picture-uri "$pic"
             ;;
         DEEPIN)
-            AssertPicture
+            AssertPicture endeavouros_deepin.png
             dconf write /com/deepin/wrap/gnome/desktop/background/picture-uri "'$pic'"  # Note: extra quotes required!
             ;;
         GNOME | GNOME3)
-            AssertPicture
+            AssertPicture endeavouros_gnome.png
             gsettings set org.gnome.desktop.background picture-uri "$pic"
             ;;
         I3)
-            AssertPicture no
+            AssertPicture endeavouros_i3.png no
             feh --bg-scale "$pic"
             ;;
         KDE)
-            AssertPicture no
+            AssertPicture endeavouros_plasma.png no
             python3 /usr/share/endeavouros/scripts/ksetwallpaper.py "$pic"
             # see also:
             # https://www.kubuntuforums.net/showthread.php/66762-Right-click-wallpaper-changer?p=387392&viewfull=1#post387392
             ;;
         LXQT)
-            AssertPicture no
+            AssertPicture endeavouros_lxqt.png no
             pcmanfm-qt --set-wallpaper="$pic"
             ;;
         MATE)
-            AssertPicture no
+            AssertPicture endeavouros_mate.png no
             gsettings set org.mate.background picture-filename "$pic"
             ;;
         XFCE)
-            AssertPicture no
+            AssertPicture endeavouros_xfce4.png no
             XfceSetWallpaper
             ;;
         *)
@@ -157,20 +154,30 @@ WallpaperSetCommon() {
 }
 
 AssertPicture() {
-    local use_file_prefix="$1"
-
-    test -n "$pic" || DIE "no picture file given!"
+    local fallback="$1"
+    local use_file_prefix="$2"
 
     case "$pic" in
-        file://*) pic="${pic:7}" ;;
-        /*)       ;;
-        *)        test -r "$pic" && pic="$PWD/$pic" ;;
+        DEFAULT | default) pic="$fallback" ;;
+    esac
+
+    # change $pic to full path format
+    case "$pic" in
+        "")       DIE "no picture file given!" ;;
+        file://*) pic="${pic:7}" ;;                         # remove prefix
+        /*)       ;;                                        # OK, full path
+        *)        if [ -r "$pic" ] ; then
+                      pic="$PWD/$pic"                       # picture in current folder
+                  elif [ -r "$picfolder/$pic" ] ; then
+                      pic="$picfolder/$pic"                 # EOS picture without path given, add path
+                  fi
+                  ;;
     esac
 
     # Now we have a full path.
     test -r "$pic" || DIE "Picture file '$pic' does not exist."
 
-    # Some DE's prefer file:// prefix.
+    # Some DE's prefer file:// prefix, some not.
     if [ "$use_file_prefix" = "no" ] ; then
         case "$pic" in
             file://*) pic="${pic:7}" ;;
@@ -181,15 +188,35 @@ AssertPicture() {
             *) pic="file://$pic" ;;
         esac
     fi
+    echo "Setting desktop wallpaper $(basename "$pic") for '$DE' ..." >&2
+}
+
+Parameters() {
+    local arg msg
+
+    for arg in "$@" ; do
+        case "$arg" in
+            -*)
+                msg="$(printf "\n%s\n\n" "Unsupported option '$arg'." ; Usage)"
+                DIE "$msg"
+                ;;
+            *)
+                pic="$arg"
+                ;;
+        esac
+    done
 }
 
 Usage() {
     cat <<EOF
 Usage: <b>$progname</b> [wallpaper-file]
 where
-       wallpaper-file     Wallpaper file name.
+    wallpaper-file     Wallpaper file name, or DEFAULT
 
-If wallpaper-file is not given, user can select a wallpaper from EndeavourOS default wallpapers.
+'wallpaper-file' value
+    - can have absolute or relative path, with or without leading 'file://'.
+    - 'DEFAULT' means the default Desktop specific wallpaper.
+If 'wallpaper-file' is not given, user can choose a wallpaper from EndeavourOS default wallpapers.
 
 EOF
 }
@@ -199,20 +226,9 @@ Main()
     local progname="$(basename "$0")"
     local DE="$(eos_yad_GetDesktopName)"
     local picfolder=/usr/share/endeavouros/backgrounds
-    local arg
     local pic=""
 
-    for arg in "$@" ; do
-        case "$arg" in
-            -*)
-                local msg="$(printf "\n%s\n\n" "Unsupported option '$arg'." ; Usage)"
-                DIE "$msg"
-                ;;
-            *)
-                pic="$arg"    # filename with absolute or relative path, and with or without leading "file://"
-                ;;
-        esac
-    done
+    Parameters "$@"
 
     if [ -z "$pic" ] ; then
         WallpaperSelect
