added function Wget2Curl

diff --git a/eos-bash-shared/eos-script-lib-yad b/eos-bash-shared/eos-script-lib-yad
--- a/eos-bash-shared/eos-script-lib-yad
+++ b/eos-bash-shared/eos-script-lib-yad
@@ -560,6 +560,49 @@ eos_FormMonoText() {
     printf "<span font='Mono$size'>%s</span>" "$txt"
 }
 
+
+Wget2Curl() {
+    # Convert a wget call to a curl call.
+    local opts
+
+    opts="$(/usr/bin/getopt -o=qO: --longoptions timeout:,user-agent: --name "$progname" -- "$@")" || {
+        PreLog "$FUNCNAME: option handling failed!"
+        return 1
+    }
+
+    eval set -- "$opts"
+
+    local cmd=(curl --fail --location)
+    local retval=0
+
+    while true ; do
+        case "$1" in
+            -q)           cmd+=(--silent)  ;;
+            -O)           cmd+=(--output "$2"); shift ;;
+            --user-agent) cmd+=($1 "$2"); shift ;;
+            --timeout)    cmd+=(--max-time $2); shift ;;
+
+            --) shift ; break ;;
+        esac
+        shift
+    done
+
+    [ "$foobar_test" = "yes" ] && echo "${cmd[*]} $*"
+
+    "${cmd[@]}" "$@"
+
+    retval=$?
+    if [ "$foobar_test" = "yes" ] ; then
+        case "$retval" in
+            23) echo "==> Write error. Curl could not write data to a local filesystem or similar." ;;
+            0) ;;
+            *) echo "==> curl returned $retval." ;;
+        esac
+    fi
+    return $retval
+}
+
+
 # check the config:
 case "$EOS_ROOTER" in
     su           | "su -c"          | "/usr/bin/su -c" | "")     export EOS_ROOTER="eos-run-cmd-with-su" ;;          # default!
