added eos-kernel-nvidia-update-check, changed UpdateInTerminal

diff --git a/eos-bash-shared/UpdateInTerminal b/eos-bash-shared/UpdateInTerminal
--- a/eos-bash-shared/UpdateInTerminal
+++ b/eos-bash-shared/UpdateInTerminal
@@ -18,17 +18,8 @@ export -f eos_yad_terminal
 export -f eos_yad_RunCmdTermBash
 
 Checkupdates() {
-    # On nvidia gpu machines, if a kernel is updated, the nvidia package(s) should be updated too.
-    # This function checks this.
-    # Note that if nvidia-dkms is installed, check is not needed.
-
     local updates
     local retval
-    local linux_lts=no
-    local linux=no
-    local nvidia_lts=no
-    local nvidia=no
-    local nvidias
 
     updates=$(checkupdates)
     retval=$?
@@ -37,24 +28,12 @@ Checkupdates() {
 
     case "$retval" in
         0)
-	    nvidias="$(/usr/bin/pacman -Qq nvidia-dkms nvidia nvidia-lts 2>/dev/null)"
-	    if [ -n "$nvidias" ] && [ -z "$(echo "$nvidias" | /usr/bin/grep nvidia-dkms)" ] ; then
-		updates=$(echo "$updates" | /usr/bin/awk '{print $1}')
-		for pkg in $updates ; do
-		    case "$pkg" in
-			linux-lts)  linux_lts=yes ;;
-			linux)      linux=yes ;;
-			nvidia-lts) nvidia_lts=yes ;;
-			nvidia)     nvidia=yes ;;
-		    esac
-		done
-		if [ "$linux_lts" = "yes" ] && [ "$nvidia_lts" = "no" ] ; then
-		    WARN "linux-lts will be upgraded but nvidia-lts not."
-		fi
-		if [ "$linux" = "yes" ] && [ "$nvidia" = "no" ] ; then
-		    WARN "linux will be upgraded but nvidia not."
-		fi
-	    fi
+            eos-kernel-nvidia-update-check "$(echo "$updates" | awk '{print $1}')" || {
+                read -p "Stop upgrade (Y/n)? " >&2
+                case "$REPLY" in
+                    "" | [Yy]*) exit 1 ;;
+                esac
+            }
 	    ;;
     esac
     return $retval
@@ -115,7 +94,7 @@ Main() {
         Checkupdates
         case "$?" in
             0) $EOS_ROOTER 'pacman -Syu' ;;
-            1) DIE "checkupdates: $(ltr updt_failure)" ;;
+            1) DIE "$(echo Checkupdates: $(ltr updt_failure) | sed 's|&#33;$|!|')" ;;  # sed: exclamation mark conversion
             2) echo2 " $(ltr updt_nothing_todo)" ;;
         esac
         [ "$checkAur" = "yes" ] && echo2 ""
