[iso-create-ml] small improvements

diff --git a/iso-create-ml/create-ml b/iso-create-ml/create-ml
--- a/iso-create-ml/create-ml
+++ b/iso-create-ml/create-ml
@@ -25,7 +25,7 @@ FetchMirrors() {
         rm -f "$fetched"
         if [ ! -e "$file" ] ; then
             operation=create
-            WARN "could not $operation $file."
+            WARN "could not update '$file'."
             return 1
         fi
     fi
@@ -33,12 +33,13 @@ FetchMirrors() {
 }
 
 FetchCountries() {
-    # [ $has_internet_connection = yes ] || return 1
-
     local info codes=() countries=()
 
     info=$(/bin/reflector --list-countries 2>/dev/null | /bin/sed -E '/^Country[ ]+Code/,/^-----/'d)
-    [ "$info" ] || return 1
+    if [ -z "$info" ] ; then
+        WARN "could not update '$dbfile'"
+        return 1
+    fi
     codes=(WW $(echo "$info" | sed -E 's|(.*[a-z])[ ]+([A-Z][A-Z])[ ]+[0-9]+|\2|'))
     readarray -t countries <<< $(echo "Worldwide"; echo "$info" | sed -E 's|(.*[a-z])[ ]+([A-Z][A-Z])[ ]+[0-9]+|\1|')
 
@@ -132,40 +133,46 @@ DumpOptions() {
 }
 
 Parameters() {
-    local opts
+    local opts tmp
 
     opts="$(/bin/getopt -o="$sopts" --longoptions "$lopts" --name "$progname" -- "$@")" || exit 1
     eval set -- "$opts"
-
 
     while [ "$1" ] ; do
         case "$1" in
             --)                  shift; break ;;
             --offline)           has_internet_connection=no ;;
-            --fake-country)      country_code="$2"; shift ;;
+            --fake-country)      tmp="$2"
+                                 shift
+                                 if [ "$tmp" ] ; then
+                                     # validate given fake country code
+                                     tmp=${tmp,,}
+                                     case "$tmp" in
+                                         [a-z][a-z]) country_code="$tmp" ;;
+                                         *)          echo "==> Country code '$tmp' not recognized. See 'reflector --list-countries'." >&2 ;;
+                                     esac
+                                 fi
+                                 ;;
             --user-countries)    UserCountriesFromFile ;;
 
             --nolocal)           local_country_wanted=no ;;
             --http | --rsync)    protocols+=("${1:2}") ;;
             --sequential)        parallel=no ;;
             --update-supports)   rm -f "$mirrordata" "$dbfile" ;;
-            --nosave)            save=no ;;
+            --save)              save=yes; target=$target_def ;;
+            --savefile)          save=yes; target="$2"; shift ;;
             --dump-options)      DumpOptions ;;
             -v | --verbose)      verbose=yes ;;
             -r | --recommended-countries)
                 # Adding recommended countries for ranking.
                 # Note that the current country will be added later if user wants it and has Arch mirrors.
-                if [ $has_internet_connection = no ] ; then
-                    countries_given+=(ww)
-                    protocols+=(http)
-                fi
                 case "$country_code" in
                     de|us|cn)    ;;
                     ca)          countries_given+=(us) ;;
                     au)          countries_given+=(ww) ;;
                     br|cl|co|mx) countries_given+=(ww us); protocols+=(http) ;;
                     fi)          countries_given+=(ww se) ;;
-                    al|at|be|cz|dk|ee|es|fr|gb|gr|hr|it|no|pl|pt|se)
+                    al|at|be|cz|dk|ee|es|fr|gb|gr|hr|it|nl|no|pl|pt|se)
                                  countries_given+=(ww de fr) ;;
                     *)           countries_given+=(ww de us); protocols+=(http) ;;
                 esac
@@ -176,12 +183,13 @@ Usage:   $progname [options] [country-code [...]]
 
 Options: --help, -h                   This help.
          --nolocal                    Do not include mirrors from the current country.
-         --offline                    Don't use internet even if a connection is available.
+         --offline                    Don't use internet if a connection is not available.
+         --save                       Save mirrorlist to $target_def (see also option --savefile).
+         --savefile=*                 File path to save the mirrorlist.
          --sequential                 Rank mirrors sequentially (slower) instead of in parallel (faster).
-         --nosave                     Do not save mirrorlist to $target.
          --verbose, -v                Show more ranking details.
-         --http                       Include mirrors with http://
-         --rsync                      Include mirrors with rsync://
+         --http                       Include the http:// mirrors.
+         --rsync                      Include the rsync:// mirrors.
          --recommended-countries, -r  Use recommended countries instead of giving a list of country codes.
                                       If this does not generate a reasonable mirrorlist
                                       (e.g. in offline mode), then give one or more country codes
@@ -189,10 +197,11 @@ Options: --help, -h                   This help.
          --user-countries             Use file $user_fav_countries to give country codes.
                                       It can contain a list of codes separated by white spaces.
          --fake-country=*             Set a fake current country code (advanced).
-         --update-supports            Update support data files that will be stored for the ISO (advanced).
 
-Notes:   * Mirrors with https:// are included by default.
-         * Country codes are two-letter codes from command 'reflector --list-countries'.
+Notes:   * Only https:// mirrors are included by default.
+         * Country codes are the two-letter codes listed by command 'reflector --list-countries'.
+         * Use option --save to change the existing $target_def.
+         * Use option --recommended-countries to rank mirrors from the recommended countries.
 EOF
                 exit 0
                 ;;
@@ -240,7 +249,7 @@ Main2() {
         {
             echo -e "### Mirror list generated at $(date "+%Y-%m-%d %X")"
             echo -e "### Command: $progname ${orig_args[*]}\n"
-            ./rankmirrors-arch "${rankmirrors_opt[@]}" "$tmplist" | column -t -s'|' | sed 's|/lastupdate|/$repo/os/$arch|'
+            rankmirrors-arch "${rankmirrors_opt[@]}" "$tmplist" | column -t -s'|' | sed 's|/lastupdate|/$repo/os/$arch|'
         } > "$mirrorlist"
         echo2 "==> Mirrors ranked."
     else
@@ -253,15 +262,25 @@ Main2() {
     fi
 
     if [ $save = yes ] ; then
-        echo2 "==> Updating $target:"
-        sudo rm -f $target.bak
-        sudo mv $target $target.bak
-        sudo cp -iv "$mirrorlist" $target
-        sudo chmod go+r $target
+        if [ "$target" = $target_def ] ; then
+            echo2 "==> Updating $target:"
+            sudo rm -f "$target.bak"
+            sudo mv "$target" "$target.bak"
+            sudo cp -iv "$mirrorlist" "$target"
+            sudo chmod go+r "$target"
+        else
+            if [ -w "${target%/*}" ] ; then
+                echo2 "==> Updating $target."
+                cp "$mirrorlist" "$target"
+            else
+                echo2 "==> Updating $target:"
+                sudo cp "$mirrorlist" "$target"
+            fi
+        fi
     else
         echo2 ""
         cat "$mirrorlist" >&2
-        echo2 "\n==> $target NOT updated because of option --nosave."
+        echo2 "\n==> $target NOT updated because option --save was not used."
     fi
     Cleanup
 }
@@ -271,13 +290,14 @@ Main() {
 
     local -r sep="|"
     local lopts sopts
-    local OPTS="help${sep}h,http,nolocal,nosave,offline,recommended-countries${sep}r,rsync,sequential"
+    local OPTS="help${sep}h,http,nolocal,save,savefile:,offline,recommended-countries${sep}r,rsync,sequential"
     OPTS+=",update-supports,user-countries,fake-country:,verbose${sep}v,dump-options"
     lopts="$(echo "$OPTS" | sed -E 's|(/.[:]*)||g')"
     sopts="$(echo "$OPTS" | sed -E 's|[^/]*/(.[:]*)[^/]*|\1|g')"
 
     local -r user_fav_countries=$HOME/user-countries.txt
-    local -r target=/etc/pacman.d/mirrorlist
+    local -r target_def=/etc/pacman.d/mirrorlist
+    local target=$target_def
     local mirrordata="arch-mirrors-active.conf"                          # support file: active Arch mirrors in various countries
     local dbfile="arch-countries.conf"                                   # support file: mappings between country-code and country-name
     local has_internet_connection=yes
@@ -285,7 +305,7 @@ Main() {
     local local_country_wanted=yes                                       # include local country in the mirrorlist or not?
     local verbose=no
     local updated_supports=no
-    local save=yes
+    local save=no
     local parallel=yes                                                   # ranking mirrors in pararallel or not?
     local protocols=(https)                                              # list of supported protocols
     local countries_given=()                                             # list of user given countries which have mirrors to include
@@ -295,36 +315,24 @@ Main() {
 
     eos-connection-checker || has_internet_connection=no
 
+    [ $has_internet_connection = yes ] && country_code="$(show-location-info --tolower country)"
+
     # handle some special options here
     local args=() arg arg2 ix tmp=("$@")
     for ((ix=0; ix < ${#tmp[@]}; ix++)) ; do
         arg="${tmp[$ix]}"
         case "$arg" in
-            --update-supports)             Parameters "$arg"; updated_supports=yes ;;
+            --update-supports)             rm -f "$mirrordata" "$dbfile"; GetSupportFiles; exit 0 ;;   # just update the support files
             --fake-country)                Parameters "$arg" "${tmp[$((ix+1))]}"; ((ix++)) ;;
             --fake-country=*)              Parameters "--fake-country" "${arg#*=}" ;;
-            --offline | --user-countries)  Parameters "$arg" ;;
+            --user-countries)              Parameters "$arg" ;;
+            --testing)                     ;;                             # --testing is not a real option for users...
             *)                             args+=("$arg") ;;
         esac
     done
-    GetSupportFiles
-    [ "$updated_supports" = yes ] && exit 0
-    
-    if [ "$country_code" ] ; then
-        # validate country code
-        country_code=${country_code,,}
-        case "$country_code" in
-            [a-z][a-z]) ;;
-            *)          echo "==> Country code '$country_code' not recognized. See 'reflector --list-countries'." >&2
-                        country_code=""
-                        ;;
-        esac
-    else
-        if [ $has_internet_connection = yes ] ; then
-            country_code="$(show-location-info --tolower country)"
-        fi
-    fi
 
+    GetSupportFiles
+    
     Parameters "${args[@]}"
 
     Main2
@@ -336,23 +344,15 @@ IsOnIso() {
 
 GetSupportFiles() {
     if [ ! -e "$mirrordata" ] ; then
-        if [ $has_internet_connection = yes ] ; then
-            if FetchMirrors ; then
-                IsOnIso && cleanup_files+=("$mirrordata")
-            else
-                mirrordata="/etc/${mirrordata##*/}"
-            fi
+        if FetchMirrors ; then
+            IsOnIso && cleanup_files+=("$mirrordata")
         else
             mirrordata="/etc/${mirrordata##*/}"
         fi
     fi
     if [ ! -e "$dbfile" ] ; then
-        if [ $has_internet_connection = yes ] ; then
-            if FetchCountries ; then
-                IsOnIso && cleanup_files+=("$dbfile")
-            else
-                dbfile="/etc/${dbfile##*/}"
-            fi
+        if FetchCountries ; then
+            IsOnIso && cleanup_files+=("$dbfile")
         else
             dbfile="/etc/${dbfile##*/}"
         fi
