[eos-rankmirrors] fixed a bug that in some cases didn't use the latest list of mirrors

diff --git a/eos-rankmirrors/eos-rankmirrors b/eos-rankmirrors/eos-rankmirrors
--- a/eos-rankmirrors/eos-rankmirrors
+++ b/eos-rankmirrors/eos-rankmirrors
@@ -38,7 +38,7 @@ ERROR() {
 
 DIE() {
     local msg="$1"
-    local level="$2" ; [ -n "$level" ] || level=0
+    local level="$2" ; [ "$level" ] || level=0
     ERROR "error detected at function ${FUNCNAME[$((level+1))]}, line ${BASH_LINENO[$level]}:" "$msg"
     DeleteTmpFiles
     Usage
@@ -254,43 +254,35 @@ CheckMirrorlist() {
         fi
     fi
 }
+ExtractListFromPackage() {
+    local -r pkg="$1"
+    [ "$pkg" ] || return 1
+    INFO "extracting $pkgname package..."
+    tar --extract -O -f "$pkg" etc/pacman.d/endeavouros-mirrorlist > $latest_ml
+}
 
 FetchLatestMirrorlist() {
-    # Grab endeavouros-mirrorlist from the package cache, or fetch it from github/gitlab.
+    # Grab endeavouros-mirrorlist from a mirror.
 
-    if [ "$use_local_mirrorlist" = "yes" ] ; then
-        # Use file /etc/pacman.d/endeavouros-mirrorlist. Remove potential ranking results first.
-        sed -e '/^# Results of mirror ranking at /,$d' -e 's|^#[ ]*Server = |Server = |' $emlpath  > $latest_ml
-        CheckMirrorlist "$latest_ml"
-        return
-    fi
-
-    local pkg=(/var/cache/pacman/pkg/${pkgname}-*.zst)
-    if [ ${#pkg[@]} -gt 0 ] ; then
-        pkg="${pkg[$(( ${#pkg[@]} - 1 ))]}"
-        # the package exists in the cache
-        local cachev=$(echo "$pkg" | sed 's|.*list-\(.*\)-any.*|\1|')
-        local installedv=$(pacman -Q $pkgname | awk '{print $2}')
-        if [ "$cachev" = "$installedv" ] ; then
-            INFO "extracting $pkg ..."
-            tar --extract -O -f "$pkg" etc/pacman.d/endeavouros-mirrorlist > $latest_ml
-            CheckMirrorlist "$latest_ml"
-            return
-        fi
-    fi
-    # package not in cache or installed package version is not the same as in cache
+    local latest_remote=$(expac -S %v $pkgname)
+    local pkg
     local code=0
-    local url="https://raw.githubusercontent.com/endeavouros-team/PKGBUILDS/master/$pkgname/$pkgname"
-    url="$(eos-github2gitlab --keep-master "$url")"
-    INFO "fetching $url ..."
-    curl --fail -Lsm $timeout -o $latest_ml $url || code=$?
-    case "$code" in
-        0) ;;
-        *) ERROR "cannot fetch EndeavourOS mirrorlist info (curl error code $code)."
-           exit 0
-           ;;
-    esac
-    CheckMirrorlist "$latest_ml"
+    local url
+    local urls=(
+        "https://mirror.alpix.eu/endeavouros/repo/endeavouros/${arch}/endeavouros-mirrorlist-${latest_remote}-any.pkg.tar.zst"
+        "https://https://mirror.moson.org/endeavouros/repo/endeavouros/${arch}/endeavouros-mirrorlist-${latest_remote}-any.pkg.tar.zst"
+    )
+
+    pkg=$(mktemp /tmp/XXXXX.tar.zst)
+    delete_at_end+=("$pkg")
+
+    for url in "${urls[@]}" ; do
+        curl --fail -Lsm $timeout -o $pkg "$url"
+        code=$?
+        [ $code -eq 0 ] && break
+    done
+    [ $code -eq 0 ] || DIE "cannot fetch EndeavourOS mirrorlist package (curl error code $code)."
+    ExtractListFromPackage "$pkg" && CheckMirrorlist "$latest_ml"
 }
 
 SimpleRank() {
@@ -745,7 +737,7 @@ Main()
 
     new=$(/usr/bin/mktemp) ; delete_at_end+=("$new")
 
-    SimpleRank > $new
+    SimpleRank > $new || DIE "ranking failed."
     [ "$hook_rank" = "no" ] && cat $new
 
     if [ -z "$(grep "^Server = " $new)" ] ; then
