[ckbcomp] small fixes to PKGBUILD

diff --git a/ckbcomp/PKGBUILD b/ckbcomp/PKGBUILD
--- a/ckbcomp/PKGBUILD
+++ b/ckbcomp/PKGBUILD
@@ -6,6 +6,7 @@
 # Ex-Maintainer:  Jeroen Bollen <jbinero at gmail dot comau>
 
 pkgname=ckbcomp
+pkgver=1.228
 pkgrel=1
 pkgdesc="Compile a XKB keyboard description to a keymap suitable for loadkeys or kbdcontrol"
 arch=(any)
@@ -21,21 +22,23 @@ _ckbcomp_preparations() {
     # - pkgver may include only numbers, lowercase letters, and "." "+" "~"
 
     local -r err="echo $pkgname: error:"
-    local INFO
+    local changed=no
 
+    # If $pkgname is installed, check if there are changes.
     if [ -x /bin/$pkgname ] ; then
         url="https://salsa.debian.org/installer-team/console-setup/raw/master/Keyboard/$pkgname"
         curl --fail -Lsm 30 -o$pkgname "$url" || exit 1
-        if diff $pkgname /bin/$pkgname >/dev/null ; then
-            echo "$pkgname: no change detected!" >&2
-            rm -f $pkgname
-            exit 1
-        fi
+        diff $pkgname /bin/$pkgname >/dev/null || changed=yes
     fi
     url="https://sources.debian.org/src/console-setup"
-    INFO=$(curl --fail -Lsm 30 "$url") || { $err "fetching version info failed"; exit 1; }
-    pkgver="$(echo "$INFO" | grep -m1 "/src/console-setup/" | sed -E 's|.*/src/console-setup/([^/]+)/.*|\1|')"
-    [ "${pkgver//[a-z0-9.+~]/}" ] && { $err "sorry, pkgver ($pkgver) is invalid"; exit 1; }
+    if [ $changed = yes ] ; then
+        # $pkgname has been changed, so get the new pkgver.
+        # Note: sha512sums for the new $pkgname must be changed manually.
+        local INFO
+        INFO=$(curl --fail -Lsm 30 "$url") || { $err "fetching version info failed"; exit 1; }
+        pkgver="$(echo "$INFO" | grep -m1 "/src/console-setup/" | sed -E 's|.*/src/console-setup/([^/]+)/.*|\1|')"
+        [ "${pkgver//[a-z0-9.+~]/}" ] && { $err "sorry, pkgver ($pkgver) is invalid"; exit 1; }
+    fi
     source=("https://sources.debian.org/data/main/c/console-setup/$pkgver/Keyboard/$pkgname")
 }
 
