made nvidia-site-check-and-update-db work without installed nvidia stuff; added polybar

diff --git a/eos-pkgbuild-setup/nvidia-site-check-and-update-db b/eos-pkgbuild-setup/nvidia-site-check-and-update-db
--- a/eos-pkgbuild-setup/nvidia-site-check-and-update-db
+++ b/eos-pkgbuild-setup/nvidia-site-check-and-update-db
@@ -3,26 +3,22 @@
 # Check at Nvidia if the GPU database has changed.
 # If it has, then offer to update the local database.
 
-DIE() {
-    echo "Error: $1" >&2
-    exit 11
-}
-
-STOP() {
-    echo "Info: $1" >&2
-    exit 3
-}
+DIE()  { echo "Error: $1" >&2 ; exit 11 ; }
+INFO() { echo "Info: $1" >&2 ; }
 
 nvidia-site-checks() {
     local ids=/var/lib/pci/nvidia.ids
     local newids=/tmp/nvidia.ids
     local retval=0
+    local differ=/usr/bin/meld   # differ of 'code' has bugs!
+
+    [ -x $differ ] || DIE "package 'meld' is required."
 
     if (! /usr/bin/ls /usr/share/licenses/nvidia* >& /dev/null) ; then
-        STOP "no Nvidia driver is installed."
+        INFO "no Nvidia driver is installed."
     fi
 
-    [ -r $ids ] || DIE "$ids does not exist!"
+    [ -r $ids ] || INFO "$ids does not exist!"
 
     rm -f /tmp/nvidia*.ids
     nvidia-installer-update-db --tmpdb 2>/dev/null
@@ -33,7 +29,7 @@ nvidia-site-checks() {
         : # echo "No changes." >&2
     else
         # /usr/bin/code --diff $ids $newids &     # bugs in diff output!
-        /usr/bin/meld $ids $newids >& /dev/null &
+        $differ $ids $newids >& /dev/null &
         echo "" >&2
         read -p "Nvidia ids are changed as shown. Update local database (y/N)? " >&2
         case "$REPLY" in
