[nvidia-installer-common] fixed nvidia-installer-kernel-para for the install process

diff --git a/nvidia-installer-common/nvidia-installer-kernel-para b/nvidia-installer-common/nvidia-installer-kernel-para
--- a/nvidia-installer-common/nvidia-installer-kernel-para
+++ b/nvidia-installer-common/nvidia-installer-kernel-para
@@ -10,10 +10,12 @@ DIE() {
 }
 
 SetKernelParameterGrub() {
-    local file=/etc/default/grub
-    [ -r $file ] || return                                              # return if grub not used
+    local file="$file_grub"
     local varname="GRUB_CMDLINE_LINUX_DEFAULT"
     local currline="$(grep ^"$varname"= $file | grep "$kernel_param")"
+    local op=""
+
+    Info "handling kernel parameter '$kernel_param' in file $file"
 
     if [ -n "$currline" ] ; then
         case "$mode" in
@@ -22,8 +24,7 @@ SetKernelParameterGrub() {
                 exit 1    # nothing changed
                 ;;
             remove)
-                Info "removing kernel parameter $kernel_param"
-                # first sed change below fails if $pname=$pvalue is first
+                # first sed change below fails if $kernel_param is first, hence the second change
                 sed -i $file \
                     -e "s|^\($varname=\".*\) $kernel_param\(.*\)$|\1\2|" \
                     -e "s|^\($varname=\".*\)$kernel_param \(.*\)$|\1\2|"
@@ -32,7 +33,10 @@ SetKernelParameterGrub() {
     else
         case "$mode" in
             add)
-                Info "adding kernel parameter $kernel_param"
+                if [ ! -e $file ] ; then
+                    Info "sorry, file $file does not exist"
+                    exit 1
+                fi
                 sed -i $file -e "s|^\($varname=\".*\)\"$|\1 $kernel_param\"|"
                 ;;
             remove)
@@ -42,45 +46,65 @@ SetKernelParameterGrub() {
                 ;;
         esac
     fi
-    cat <<EOF >&2
-Info: kernel parameters for grub will be changed by $progname, so it is advisable to run commands:
-    grub-mkconfig -o $grubcnf
-    grub-install (with proper parameters for your system!)
-EOF
-    exit 0 # parameter changed
+
+    # parameter changed
+
+    case "$mode" in
+        add)    op="added to" ;;
+        remove) op="removed from" ;;
+    esac
+    Info "kernel parameter '$kernel_param' $op $varname in file $file"
+
+    if [ "$bootloader" = "" ] ; then
+        Info "kernel parameter for grub was changed by $progname, so it is advisable to run commands:"
+        Info "    grub-mkconfig -o /boot/grub/grub.cfg"
+        Info "    grub-install (with proper parameters for your system!)"
+    fi
+    exit 0
 }
 
 SetKernelParameterSdboot() {
-    local file=/etc/kernel/cmdline
-    [ -r $file ] || return                                              # return if sd-boot not used
-
+    local file=$file_sdboot
     local paramline=$(grep "$kernel_param" $file)
+
+    Info "handling kernel parameter '$kernel_param' in file $file"
 
     case "$mode" in
         add)
-            [ "$paramline" != "" ] && exit 1                            # 1 = nothing changed
+            if [ "$paramline" != "" ] ; then
+                Info "already set: '$paramline'"
+                exit 1                            # 1 = nothing changed
+            fi
             Info "adding kernel parameter: $kernel_param"
-            if [ "$(stat -c %s $file)" = "0" ] ; then
+            if [ ! -e $file ] || [ "$(stat -c %s $file)" = "0" ] ; then
                 echo "$kernel_param" > $file
             else
                 sed -E -i $file -e "s|([ \t]*[^#].*)|$kernel_param \1|"     # insert to a non-comment line
             fi
             ;;
         remove)
-            [ "$paramline" = "" ] && exit 1                             # 1 = nothing changed
+            if [ "$paramline" = "" ] ; then
+                Info "already removed: '$paramline'"
+                exit 1                             # 1 = nothing changed
+            fi
             Info "removing kernel parameter: $kernel_param"
             sed -E -i $file -e "s|$kernel_param[ ]{0,1}||g"
             ;;
     esac
 
-    [ "$ccs" = "no" ] && reinstall-kernels    # run reinstall-kernels only if not called from ccs
+    if [ "$bootloader" = "" ] ; then
+        Info "running reinstall-kernels after changing kernel parameter"
+        reinstall-kernels    # run reinstall-kernels only if not called from ccs
+    fi
     exit 0   # parameter changed
 }
 
 Options() {
     local opts
+    local sopts="h"
+    local lopts="help,bootloader:"
 
-    opts="$(/usr/bin/getopt -o=h --longoptions help,ccs --name "$progname" -- "$@")" || {
+    opts="$(/usr/bin/getopt -o=$sopts --longoptions $lopts --name "$progname" -- "$@")" || {
         Options --help
         return 1
     }
@@ -89,7 +113,7 @@ Options() {
 
     while true ; do
         case "$1" in
-            --ccs) ccs=yes ;;
+            --bootloader) bootloader="$2" ; shift ;;
 
             --) shift ; break ;;
 
@@ -123,7 +147,7 @@ Main() {
     local mode=""               # optional: add (default) or remove
 
     # variables to store option values
-    local ccs=no
+    local bootloader=""
 
     Options "$@" || return 1
 
@@ -135,10 +159,29 @@ Main() {
         *) DIE "$progname: error: value '$mode' for the second parameter is not supported" ;;
     esac
 
-    SetKernelParameterSdboot      # exits if using sd-boot
-    SetKernelParameterGrub        # exits if using grub
+    local file_sdboot=/etc/kernel/cmdline
+    local file_grub=/etc/default/grub
 
-    Info "sd-boot or grub not in use"
+    # TESTING !!!
+    file_sdboot=$HOME/cmdline.test
+    file_grub=$HOME/grub.test
+
+    case "$bootloader" in
+        "")
+            [ -r $file_sdboot ] && SetKernelParameterSdboot
+            [ -r $file_grub ] && SetKernelParameterGrub
+            Info "systemd-boot or grub not in use"
+            ;;
+        systemd-boot)
+            SetKernelParameterSdboot
+            ;;
+        grub)
+            SetKernelParameterGrub
+            ;;
+        *)
+            Info "sorry, $progname does not currently support $bootloader bootloader."
+            ;;
+    esac
 }
 
 Main "$@"
