[nvidia-installer-common] changed Nvidia site URL, thanks to Schplatter report

diff --git a/nvidia-installer-common/nvidia-driver-supported-branches b/nvidia-installer-common/nvidia-driver-supported-branches
--- a/nvidia-installer-common/nvidia-driver-supported-branches
+++ b/nvidia-installer-common/nvidia-driver-supported-branches
@@ -10,40 +10,9 @@ DIE() {
     exit 1
 }
 
-if false ; then
-GetNvidiaIds_old()
-{
-    local version="$1"
-    local ids="$(curl -Lsm $curl_timeout -o- https://us.download.nvidia.com/XFree86/Linux-x86_64/$version/README/supportedchips.html)"
-    local true_series="${version%%.*}"
-
-    [ -n "$ids" ] || DIE "fetcing supported ids for $version failed"
-
-    ids="$(echo "$ids" | sed -n '1,/.*Below are the legacy GPUs that are no longer supported.*/p' | grep '<tr id=')"
-
-    # old (340 series):
-    #    <tr id="0x064C">                   # take 064C
-    #
-    # new (390 ... ):
-    #    <tr id="devid17FD_10DE_1173">      # take 17FD
-    #    <tr id="devid17FD">                # take 17FD
-
-    if [ -n "$(echo "$ids" | grep 'id="devid')" ] ; then
-        ids="$(echo "$ids" | grep '<tr id="devid' | sed 's|.*devid\([0-9A-F]*\)["_].*|\1|')"        # new
-    else
-        ids="$(echo "$ids" | sed 's|.*id="0x\([0-9A-F]*\)">|\1|')"                                  # old
-    fi
-
-    ids=$(echo "$ids" | sort | uniq | tr '[:upper:]' '[:lower:]')
-    echo "$true_series|$ids"
-}
-fi
-
 FilterIds() {
     # supports series 390 and later
     grep '<tr id="devid' | sed 's|.*devid\([0-9A-F]*\)["_].*|\1|' | sort -u | tr '[:upper:]' '[:lower:]'
-
-    # grep 'id="devid' | grep '<tr id="devid' | sed 's|.*devid\([0-9A-F]*\)["_].*|\1|' | sort -u | tr '[:upper:]' '[:lower:]'
 }
 
 GetNvidiaIds() {
@@ -102,7 +71,9 @@ ShowDriversForId() {
             fi
             case "$true_series" in
                 ${series_ids[1]} | ${series_ids[2]} | 470 | 390)
-                    printf2 "NOTE: nvidia-inst does not support series $true_series. To install, use the 'yay' command.\n"
+                    if [ $hide_nvidia_inst_msgs = no ] ; then
+                        printf2 "NOTE: nvidia-inst does not support series $true_series. You can install the driver using 'yay'.\n"
+                    fi
                     ;;
             esac
             [ "$all" = "no" ] && return
@@ -148,7 +119,7 @@ GetNvidiaVersions() {
 Options() {
     local opts
 
-    opts="$(/usr/bin/getopt -o=hajt: --longoptions help,all,test,timeout: --name "$progname" -- "$@")" || {
+    opts="$(/usr/bin/getopt -o=hajt: --longoptions help,all,test,timeout:,hide-nvidia-inst-msgs --name "$progname" -- "$@")" || {
         Options -h
         return 1
     }
@@ -160,6 +131,10 @@ Options() {
             -a | --all) echo2 "Info: option '$1' recognized but is no more used." ;; # all=yes ;;
             -j | --test) testing=yes ;;
             -t | --timeout) curl_timeout="$2" ;;
+            --hide-nvidia-inst-msgs)
+                # Do not show messages related to program nvidia-inst.
+                hide_nvidia_inst_msgs=yes
+                ;;
 
             -h | --help)
                 cat <<EOF >&2
@@ -194,14 +169,16 @@ EOF
     nvidia_id="$1"
 
     case "$nvidia_id" in
-        [0-9a-f][0-9a-f][0-9a-f][0-9a-f] | "") ;;
-        *) DIE "given card id '$nvidia_id' is invalid" ;;
+        "") ;;
+        [0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f]) nvidia_id=${nvidia_id,,} ;;
+        *) DIE "given card id '$nvidia_id' is invalid, must contain only hexadecimal numbers (0-9 a-f A-F)" ;;
     esac
 }
 
 UrlOfIds() {
     local ver="$1"
-    echo "https://us.download.nvidia.com/XFree86/Linux-x86_64/$ver/README/supportedchips.html"
+    echo "https://download.nvidia.com/XFree86/Linux-x86_64/$ver/README/supportedchips.html"
+    # echo "https://us.download.nvidia.com/XFree86/Linux-x86_64/$version/README/supportedchips.html"   # no more works (?)
 }
 
 GetPacmanVersion() {
@@ -228,6 +205,7 @@ Main() {
     local curl_timeout=$curl_timeout_default
     local nvidia_id=""
     local nvidia_versions=()
+    local hide_nvidia_inst_msgs=no
     local -r beta_pkg=nvidia-beta-dkms
     local -r beta_pkgver=$(yay -Ss $beta_pkg | grep ^aur/ | awk '{print $2}' | sed 's|-[0-9.]*$||')
     local -r beta_series=${beta_pkgver%%.*}
