installing some EOS hooks

diff --git a/endeavouros-theming/PKGBUILD b/endeavouros-theming/PKGBUILD
--- a/endeavouros-theming/PKGBUILD
+++ b/endeavouros-theming/PKGBUILD
@@ -1,7 +1,7 @@
 # Maintainer: joekamprad <joekamprad@endeavouros.com>
 pkgname=endeavouros-theming
 pkgver=5
-pkgrel=1
+pkgrel=2
 pkgdesc='Default EndeavourOS background images and icons for all different DE'
 arch=('any')
 replaces=('EndeavourOS-theming')
@@ -24,4 +24,18 @@ package() {
         cd "${srcdir}/${pkgname}-${pkgver}/backgrounds"
 	install -d "${pkgdir}/usr/share/endeavouros/backgrounds"
 	install -m644 *.png "${pkgdir}/usr/share/endeavouros/backgrounds"
+
+        local hook
+        local folder=etc/pacman.d/hooks
+        local source=https://raw.githubusercontent.com/endeavouros-team/EndeavourOS-archiso/master/airootfs/$folder
+        install -d $pkgdir/$folder
+        for hook in os-release.hook lsb-release.hook ; do
+            if [ ! -r /$folder/$hook ] ; then
+               wget -q --timeout=20 $source/$hook || {
+                    echo "Failed to fetch hook '$hook'."
+                    return 1
+               }
+               install -m644 $hook $pkgdir/$folder/$hook
+            fi
+        done
 }
