[eos-update] started adding translation support via bash-all-translate - only a small part implemented for now

diff --git a/eos-update/eos-update b/eos-update/eos-update
--- a/eos-update/eos-update
+++ b/eos-update/eos-update
@@ -9,9 +9,9 @@ printf2() {
     printf "$@" >&2
 }
 
-INFO()    { echo2info    "==> $progname: info: $1"; }
-WARN()    { echo2warning "==> $progname: warning: $1"; }
-DIE()     { echo2error   "==> $progname: error: $1"; exit 1;  }
+INFO()    { echo2info    "==> $progname: $(BTR eup_msg_info): $1"; }
+WARN()    { echo2warning "==> $progname: $(BTR eup_msg_warning): $1"; }
+DIE()     { echo2error   "==> $progname: $(BTR eup_msg_error): $1"; exit 1;  }
 
 UseColor() { [ "$use_colors" = yes ] && eos-color "$@" 2 ; }
 
@@ -24,7 +24,7 @@ SetHelper() {
     for helper in "$@" "$EOS_AUR_HELPER" "$EOS_AUR_HELPER_OTHER" yay paru pacman ; do
         which "${helper%% *}" &>/dev/null && return 0
     done
-    WARN "AUR helper not found"
+    WARN "$(BTR eup_msg_helper_missing)"
     helper=pacman
 }
 
@@ -33,16 +33,16 @@ CmdShow() {
     "$@"
 }
 TRY() {                           # Show a command, run it, and exit on issues.
-    CmdShow "$@" || DIE "'$*' failed."
+    CmdShow "$@" || DIE "'$*' $(BTR die_result_failed)."
 }
 
 MirrorCheckResult() {
     local ml="$1"
     local ret=0
 
-    echo2 "==> $ml contains:"
-    echo2 "    available mirrors:   ${#supported[@]}"
-    echo2 "    unavailable mirrors: ${#unsupported[@]}"
+    echo2 "$(BTR msg_file_contains "$ml")"       # "==> $ml contains:"
+    echo2 "$(BTR msg_avail_mirrors   ${#supported[@]})"
+    echo2 "$(BTR msg_unavail_mirrors ${#unsupported[@]})"
     [ ${#unsupported[@]} -gt 0 ] && printf "%s\n" "${unsupported[@]}" | sed 's|^[0-9]*:|      -> Server = |' >&2
 
     if [ ${#unsupported[@]} -eq 0 ] && [ ${#supported[@]} -gt 0 ] ; then     # create the return code, 0=success, 1=fail
@@ -165,8 +165,13 @@ ResetKeyrings() {
 }
 
 ClearDatabases() {
-    TRY sudo rm -r /var/lib/pacman/sync
-    echo2 "Package databases cleared."
+    if [ -e /var/lib/pacman/sync ] ; then
+        TRY sudo rm -r /var/lib/pacman/sync
+        echo2 "Package databases cleared."
+    fi
+    TRY sudo pacman -Sy
+    TRY sudo pacman -Fy
+    echo2 "Package databases updated."
     exit 0
 }
 CheckPackageDatabases() {
@@ -474,6 +479,111 @@ Options() {
 }
 
 Usage() {
+    echo \
+"$progname is a package updater for EndeavourOS and Arch.
+
+$progname is implemented as a wrapper around commands pacman and optionally yay/paru.
+Essentially runs commands 'pacman -Syu' and optionally 'yay -Sua' or 'paru -Sua'.
+
+$progname includes (by default) special help in the following situations:
+- Prevents reboot, shutdown, hibernate, and suspend while $progname is running.
+- A dangling pacman db lock file (/var/lib/pacman/db.lck).
+- Disk space availability for updates (with a configurable minimum space).
+- Keyring package updating before updating other packages.
+- Running the 'sync' command after update.
+
+Optional help:
+- Can clear package databases in case of constant problems with them.
+- Can reset keyrings in case of constant problems with them.
+- Can check the validity of the locally configured lists of mirrors.
+- Updates AUR packages (with option --helper, see Usage below).
+- Ad hoc check for Nvidia GPU driver vs. kernel updates (non-dkms only).
+- Provides a way for users to include additional commands before and after $progname does its essentials.
+and more, see below.
+
+Usage: $progname [options]
+Options:
+  --help, -h              This help.
+  --tips                  Tips and examples for $progname.
+  --rank-mirrors          (Deprecated, see --other-updates. Will be removed at ${DeprecationDates[--rank-mirrors]}).
+                          Executes user-written bash script $rank_command_file which may contain
+                          ranking commands for both Arch and EndeavourOS mirrors, and exits.
+                          Example commands:
+                              reflector -phttps -c 'your-country-spec' | sudo tee $aml
+                              eos-rankmirrors --timeout 4
+                          See 'reflector --list-countries' to see supported country codes and names
+                          for 'your-country-spec'.
+    
+  --check-mirrors         Check files $eml and $aml
+                          for unsupported mirrors.
+                          This may be useful when one or more mirrors start failing unexpectedly.
+                          Note: only x86_64 hardware is supported.
+  --check-mirrors-eos     Check file $eml for unsupported mirrors.
+  --check-mirrors-arch    Check file $aml for unsupported mirrors.
+  --edit-mirrorlist <val> Edit chosen mirrorlist file. Supported values: arch, endeavouros. No default.
+  --reset-pacmanconf      Replace your current $pacmanconf with the EndeavourOS original.
+                          Note: do this only if you need to restore the original file.
+  --fast                  Do a *fast check* for updates in order to reduce the amount of network traffic.
+                          Note that the fast check
+                             * applies to only updates on EndeavourOS and Arch repos, and optionally on AUR
+                             * in special cases may not detect available updates; if so, run
+                               $progname without option --fast
+  --descriptions, -d      Show the descriptions of the packages to be updated. Note: AUR not supported.
+  --nvidia                Check also nvidia driver vs. kernel updates. Useful only with the Nvidia GPU.
+  --check-databases       Check for the package database being corrupted or not.
+  --clear-databases       Clears package database files.
+                          Use this only if package database issues constantly make system update fail.
+  --keyrings-reset        Resets Arch and EndeavourOS keyrings.
+                          Use this only if keyring issues constantly make system update fail.
+  --no-keyring            Do not try to update keyrings first.
+  --no-sync               Do not run 'sync' after update.
+  --keep-system-running   Protects your system from unintentional sleep, hibernate, reboot, or shutdown
+                          if '$progname' is still running. This is the default.
+  --no-keep-system-running
+                          The opposite of --keep-system-running.
+                          Allows (unintentional) sleep, hibernate, reboot, or shutdown to crash
+                          the update process, which obviously can create severe system stability issues.
+                          Don't use this unwittingly.
+  --run-mode <val>        Specifies the mode how the updating commands will be executed.
+                          Supported values:
+                             plain   Use current privileges. Uses 'sudo' for commands that need it.
+                                     If $progname was executed as root, mode changes from plain to login.
+                             root    Use elevated privileges. Impersonate $LOGNAME for the AUR helper.
+                             login   Use elevated privileges. Login as $LOGNAME for the AUR helper.
+                          Default: plain.
+  --show-only-fixed       Show only packages that have already been fixed (runs: arch-audit -u) and exit.
+  --show-upstream-news    Show the news page of the upstream site and exit.
+  --pacdiff               (Deprecated, see --other-updates. Will be removed at ${DeprecationDates[--pacdiff]}).
+                          Run eos-pacdiff in the end of $progname. See also EOS_UPDATE_PACDIFFER
+  			  in file /etc/eos-script-lib-yad.conf.
+  --cache-limit, -l <val> Runs 'paccache -rk <val>' after updates. Limits the size of the package cache.
+                          Supported numbers for <val>: 1..5.
+  --colors <val>          Enable or disable using additional colors in output. By default they are enabled.
+                          Supported values: 'yes' or 'no'.
+  --helper <val>          AUR helper name. Supported values: yay, paru, pacman.
+                          Default: pacman
+                          Other AUR helpers supporting option -Sua like yay should work as well.
+  --paru                  Same as --helper=paru.
+  --yay                   Same as --helper=yay.
+  --aur                   Uses the AUR helper configured in /etc/eos-script-lib-yad.conf.
+  --pacman                Same as --helper=pacman. Default. (Note: pacman does not support AUR directly).
+  --min-free-bytes <val>  Minimum amount of free space (in bytes) that the root partition should have
+                          before updating. Otherwise a warning message will be displayed.
+                          Default: $min_free_bytes
+  --other-updates         Enable support for *user-defined* other updates (e.g. 'flatpak update').
+                          Note that user-defined commands can be performed in the beginning and end
+                          of execution of eos-update, see $otherUpdatesFile.
+  --conf-filename         Show the name of the configuration file.
+                          Tip: to edit the config file with 'nano':
+                              sudo nano \$($progname --conf-filename)
+
+Tip: preferred options can be added to variable EOS_UPDATE_OPTIONS in file $eosupdateconf.
+
+" >&2
+    [ "$1" ] && exit "$1"
+}
+
+Usage_foo() {
     cat <<EOF >&2
 $progname is a package updater for EndeavourOS and Arch.
 
@@ -691,21 +801,23 @@ _EosUpdate_Main2() {
 
     SingleOptions "${args[@]}"
 
-    echo2tip "$progname: package updater with additional features."
-    echo2tip "Command: $progname" "${args[@]}" "\n"
+    eos-color tip 2
+    echo2 "############################################################################"
+    echo2 "## $(BTR tip_prog_purpose "$progname")"
+    echo2 "############################################################################"
+    eos-color reset 2
+    echo2 "$(BTR tip_used_command "$progname")" "${args[@]}" "\n"
 
     RunUserCommands beginning
 
     DebugBreak
-    # shellcheck disable=2119
-    _init_translations
 
     Options "${args[@]}"
 
     if [ $eufast = yes ] ; then
         eos-update-fast "${eufast_opt[@]}"
         case "$?" in
-            2) echo2 "$(ltr sysup_no)" ; exit ;;
+            2) echo2 "$(BTR sysup_no)" ; exit ;;
         esac
     fi
 
@@ -723,7 +835,7 @@ _EosUpdate_Main2() {
     DiskSpace
 
     if [ -e $lock ] && sudo fuser $lock &>/dev/null ; then
-        echo2error "==> File $lock is in use.\n    Check if another process is still managing packages."
+        echo2error "$(BTR filelock_err "$lock")"
         exit 1
         # DIE "file $lock is in use. Check if another process is still managing packages."
         #rmopt=i
@@ -743,7 +855,7 @@ _EosUpdate_Main2() {
     RunUserCommands              # deprecated, only for backwords compatibility
     RunUserCommands end
 
-    echo2tip "==> All done!"
+    echo2tip "$(BTR tip_all_done)"
     echo ""                      # this line is meant to reset cursor color to default
 }
 
@@ -783,7 +895,7 @@ HandleExtraCommands() {
                 CmdShow eos-update-descriptions --title "descriptions" --header no "${updates[@]}"
                 ;;
             --nvidia)
-                CmdShow eos-kernel-nvidia-update-check "${updates[@]}" || WARN "'Nvidia & kernel' check failed."
+                CmdShow eos-kernel-nvidia-update-check "${updates[@]}" || WARN "$(BTR warn_nvidia_chk_fail)"
                 ;;
             --keyrings | --keyring)
                 # Update certain packages before others.
@@ -793,7 +905,7 @@ HandleExtraCommands() {
                 [ "${update_first[0]}" ] && TRY sudo pacman -S --noconfirm "${update_first[@]}"
                 ;;
             *)
-                WARN "parameter '$1' ignored."
+                WARN "$(BTR warn_param_ignored "$1")"
                 ;;
         esac
         shift
@@ -804,8 +916,9 @@ HandleExtraCommands() {
 DebugBreak() { : ; }
 
 Main() {
-    local prog_name="${0##*/}"
-    local -r eosupdateconf=/etc/$prog_name.conf
+    local -r progname="${0##*/}"
+    source /usr/share/endeavouros/translations/bash-app-translate "$progname" || exit 1
+    local -r eosupdateconf=/etc/$progname.conf
     local keep_running=yes      # default execution mode
     local use_config_file=yes
     local params=()
@@ -835,7 +948,7 @@ Main() {
         esac
     done
     if [ "$keep_running" = yes ] && [ $phase = 1 ] ; then
-        local cmd=(systemd-inhibit --who="$prog_name" --why="Updating." "$prog_name" --phase=2 "${params[@]}")
+        local cmd=(systemd-inhibit --who="$progname" --why="$(BTR msg_why_sys_running)" "$progname" --phase=2 "${params[@]}")
         "${cmd[@]}"
     else
         _EosUpdate_Main2 "${params[@]}"
